[GITHUB ACTIONS] JDR-Generator : Configuration du workflow de linting, formatting et analyse statique - OK/DONE : pour les modules Gemini et Openai - OK/WIP : pour le module Web (mais bypass de rules dans eslint à fixer) - OK/WIP : Code quality module API : WIP Spotbugs buginstances skipped
Rappel des ports de l'application :
- mysql-container: 3306
- api-container: 8080
- web-container: 80
- gemini-container: 3001
- openai-container: 3002

Signed-off-by: NeoRyu <coupez.frederic@gmail.com>

diff --git a/.github/workflows/code-quality.yml b/.github/workflows/code-quality.yml
--- a/.github/workflows/code-quality.yml
+++ b/.github/workflows/code-quality.yml
@@ -52,12 +52,6 @@ jobs:
             exit 1
           fi
         id: analyze_pmd
-      - name: Fail if Priority 1 Errors
-        if: steps.analyze_pmd.outputs.priority1_errors > 0
-        run: |
-          cd api 
-          echo "Priority 1 PMD errors found. Failing the build."
-          exit 1
       - name:  Summary
         if: always()
         run: |
@@ -71,9 +65,18 @@ jobs:
             echo "Priority 1 Errors: $priority1_count"
             echo "Priority 2 Errors: $priority2_count"
             echo "Priority 3 Errors: $priority3_count"
+            echo "priority1_errors=$priority1_count" >> "$GITHUB_OUTPUT"
           else
             echo "Error: target/pmd.xml not found for Summary..."
+            echo "priority1_errors=0" >> "$GITHUB_OUTPUT"
           fi
+        id: summary_results
+      - name: Fail if Priority 1 Errors
+        if: steps.summary_results.outputs.pmd_analyzed == 'true' && steps.summary_results.outputs.priority1_errors > 0
+        run: |
+          cd api 
+          echo "Priority 1 PMD errors found. Failing the build."
+          exit 1
       # Exécution de Dependency Check
       - name: API Maven Dependency Check
         run: cd api && mvn --batch-mode org.owasp:dependency-check-maven:check
